version: '3'
services:
  backend_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-curso-dev
    restart: always
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@email.com
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
